"""Turns join.py's playlist-chart-versions.csv into the Phoenix-era half of the chart-versions
backfill script (docs/design/chart-versions.md §5), and stitches the pumpout extractor's S6 onto
it so the owner runs one idempotent file.

usage: python emit-backfill.py playlist-chart-versions.csv [s6-chart-versions-backfill.sql] > chart-versions-backfill.sql

What the script does, in order, inside one transaction with a @WhatIf switch (1 = report and roll
back, 0 = commit):
  1. Phoenix and Phoenix 2 assignments by chart id, one UPDATE per (mix, version), only rows still
     NULL — a re-run is harmless and a hand fix is never overwritten.
  2. The two charts the 2.12.0 playlist and the wiki list as new charts on an existing song but the
     catalog had as XX debuts — La Cinquantaine S22 and D24: origin → Phoenix (owner decision D9).
  3. Every remaining Phoenix / Phoenix 2 ChartMix row → that mix's 1.00.0: present at launch.
  4. The extractor's S6 body (legacy mixes), when given.
"""
import csv, sys, collections

MIX_IDS = {
    'Phoenix': '1ABB8F5A-BDA3-40F0-9CE7-1C4F9F8F1D3B',
    'Phoenix2': 'A9B7D3C1-52E8-4F06-9B1A-2F8C33E01948',
}
XX_ID = '20F8CCF8-94B1-418D-B923-C375B042BDA8'


def chunks(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def main():
    rows = list(csv.DictReader(open(sys.argv[1], encoding='utf-8')))
    s6 = open(sys.argv[2], encoding='utf-8-sig').read() if len(sys.argv) > 2 else None
    out = []
    w = out.append
    w("-- Chart versions backfill: the patch each chart arrived in, per mix (docs/design/chart-versions.md §5).")
    w("-- Generated by tools/YouTubePlaylists/emit-backfill.py. Idempotent: only rows still NULL are touched.")
    w("-- Preview first: @WhatIf = 1 reports the counts and rolls back; @WhatIf = 0 commits.")
    w("SET NOCOUNT ON;")
    w("SET XACT_ABORT ON;")
    w("DECLARE @WhatIf bit = 1;")
    w("BEGIN TRAN;")
    w("")
    w("-- ============ 1. Phoenix + Phoenix 2, from Andamiro's per-version playlists and NamuWiki ============")
    by = collections.defaultdict(list)
    for r in rows:
        by[(r['mix'], r['version'])].append(r['chartId'])
    for (mix, version), ids in sorted(by.items()):
        w(f"-- {mix} {version}: {len(ids)} charts")
        for chunk in chunks(ids, 500):
            in_list = ', '.join(f"'{i}'" for i in chunk)
            w("UPDATE cm SET [AddedInVersionId] = v.[Id]")
            w("FROM [scores].[ChartMix] cm")
            w(f"JOIN [scores].[MixVersion] v ON v.[MixId] = cm.[MixId] AND v.[Name] = N'{version}'")
            w(f"WHERE cm.[MixId] = '{MIX_IDS[mix]}' AND cm.[AddedInVersionId] IS NULL AND cm.[ChartId] IN ({in_list});")
    w("")
    w("-- ============ 2. new charts on an old song, filed as XX debuts: La Cinquantaine S22 / D24 debuted in Phoenix (D9) ============")
    mislabeled = [r for r in rows if r['mix'] == 'Phoenix' and r['origin'] == 'XX' and r['version'] == '2.12.0']
    assert [r['song'] for r in mislabeled] == ['La Cinquantaine', 'La Cinquantaine'], mislabeled
    for r in mislabeled:
        w(f"-- {r['song']} {r['type'][0]}{r['level']}")
        w(f"UPDATE [scores].[Chart] SET [OriginalMixId] = '{MIX_IDS['Phoenix']}' WHERE [Id] = '{r['chartId']}' AND [OriginalMixId] = '{XX_ID}';")
    w("")
    w("-- ============ 3. everything else in Phoenix / Phoenix 2 was present at launch ============")
    for mix, mix_id in MIX_IDS.items():
        w("UPDATE cm SET [AddedInVersionId] = v.[Id]")
        w("FROM [scores].[ChartMix] cm")
        w("JOIN [scores].[MixVersion] v ON v.[MixId] = cm.[MixId] AND v.[Name] = N'1.00.0'")
        w(f"WHERE cm.[MixId] = '{mix_id}' AND cm.[AddedInVersionId] IS NULL;")
    w("")
    if s6:
        w("-- ============ 4. legacy mixes, from the pumpout extractor (S6) ============")
        for line in s6.splitlines():
            if line.startswith(('SET XACT_ABORT', 'BEGIN TRAN', 'COMMIT TRAN')):
                continue
            w(line)
        w("")
    w("-- ============ what happened ============")
    w("SELECT m.[Name] AS Mix, v.[Name] AS Version, COUNT(*) AS Charts")
    w("FROM [scores].[ChartMix] cm JOIN [scores].[MixVersion] v ON v.[Id] = cm.[AddedInVersionId] JOIN [scores].[Mix] m ON m.[Id] = cm.[MixId]")
    w("GROUP BY m.[Name], m.[SortOrder], v.[Name], v.[SortOrder] ORDER BY m.[SortOrder], v.[SortOrder];")
    w("SELECT m.[Name] AS Mix, COUNT(*) AS StillUnknown FROM [scores].[ChartMix] cm JOIN [scores].[Mix] m ON m.[Id] = cm.[MixId]")
    w("WHERE cm.[AddedInVersionId] IS NULL GROUP BY m.[Name], m.[SortOrder] ORDER BY m.[SortOrder];")
    w("IF @WhatIf = 1 BEGIN ROLLBACK TRAN; PRINT 'WhatIf: rolled back.'; END ELSE BEGIN COMMIT TRAN; PRINT 'Committed.'; END")
    sys.stdout.reconfigure(encoding='utf-8')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
