"""Turns song-channels.csv into the SongMix backfill: one row per (song, mix) pair that has charts
and no row yet, the song's channel repeated onto every mix it is in, JMusic written as WorldMusic
on Phoenix 2, which folded the channel (docs/design/song-channels.md §7).

usage: python emit-backfill.py song-channels.csv chartmix.tsv > song-channels-backfill.sql
chartmix.tsv: MixName <tab> SongId <tab> ChartId <tab> ChartType — every ChartMix row, the mix by
the name scores.Mix carries.

One transaction with a @WhatIf switch (1 = report and roll back, 0 = commit); idempotent, so a
re-run inserts nothing and a hand-set row is never overwritten."""
import collections, csv, sys
from channels import token

FOLDED = {('Phoenix2', 'JMusic'): 'WorldMusic'}


def chunks(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def main():
    channels = {}
    for r in csv.DictReader(open(sys.argv[1], encoding='utf-8-sig')):
        ch = token(r.get('channel') or r.get('folder'))
        if ch:
            channels[r['songId'].upper()] = ch
    pairs = set()
    for line in open(sys.argv[2], encoding='utf-8-sig'):
        p = line.rstrip('\n').split('\t')
        if len(p) >= 2:
            pairs.add((p[0], p[1].upper()))
    rows = []
    unknown = collections.Counter()
    for mix, song_id in sorted(pairs):
        ch = channels.get(song_id)
        if ch is None:
            unknown[mix] += 1
            continue
        rows.append((mix, song_id, FOLDED.get((mix, ch), ch)))

    out = []
    w = out.append
    w('-- Song channels backfill: one SongMix row per (song, mix) pair with charts (docs/design/song-channels.md §7).')
    w('-- Generated by tools/SongChannels/emit-backfill.py. Idempotent: a pair that already has a row is left alone.')
    w('-- Preview first: @WhatIf = 1 reports the counts and rolls back; @WhatIf = 0 commits.')
    w('SET NOCOUNT ON;')
    w('SET XACT_ABORT ON;')
    w('DECLARE @WhatIf bit = 1;')
    w('BEGIN TRAN;')
    w('')
    by_mix = collections.Counter(mix for mix, _, _ in rows)
    for mix, n in sorted(by_mix.items()):
        w(f'-- {mix}: {n} rows' + (f' ({unknown[mix]} songs with no channel left alone)' if unknown[mix] else ''))
    w('')
    for chunk in chunks(rows, 500):
        values = ',\n'.join(f"    ('{song_id}', N'{mix}', N'{ch}')" for mix, song_id, ch in chunk)
        w('INSERT INTO [scores].[SongMix] ([SongId], [MixId], [Channel])')
        w('SELECT v.[SongId], m.[Id], v.[Channel]')
        w('FROM (VALUES')
        w(values)
        w(') v ([SongId], [MixName], [Channel])')
        w('JOIN [scores].[Mix] m ON m.[Name] = v.[MixName]')
        w('WHERE NOT EXISTS (SELECT 1 FROM [scores].[SongMix] sm WHERE sm.[SongId] = v.[SongId] AND sm.[MixId] = m.[Id]);')
        w('')
    w('-- ============ what happened ============')
    w('SELECT m.[Name] AS Mix, sm.[Channel], COUNT(*) AS Songs')
    w('FROM [scores].[SongMix] sm JOIN [scores].[Mix] m ON m.[Id] = sm.[MixId]')
    w('GROUP BY m.[Name], m.[SortOrder], sm.[Channel] ORDER BY m.[SortOrder], sm.[Channel];')
    w('-- songs with charts in a mix and still no channel there')
    w('SELECT m.[Name] AS Mix, COUNT(DISTINCT c.[SongId]) AS StillMissing')
    w('FROM [scores].[ChartMix] cm JOIN [scores].[Chart] c ON c.[Id] = cm.[ChartId] JOIN [scores].[Mix] m ON m.[Id] = cm.[MixId]')
    w('WHERE NOT EXISTS (SELECT 1 FROM [scores].[SongMix] sm WHERE sm.[SongId] = c.[SongId] AND sm.[MixId] = cm.[MixId])')
    w('GROUP BY m.[Name], m.[SortOrder] ORDER BY m.[SortOrder];')
    w("IF @WhatIf = 1 BEGIN ROLLBACK TRAN; PRINT 'WhatIf: rolled back.'; END ELSE BEGIN COMMIT TRAN; PRINT 'Committed.'; END")
    sys.stdout.reconfigure(encoding='utf-8')
    print('\n'.join(out))
    print(f'-- {len(rows)} rows across {len(by_mix)} mixes; {sum(unknown.values())} (song, mix) pairs had no channel', file=sys.stderr)


if __name__ == '__main__':
    main()
