using System.Security.Cryptography;
using System.Text;

namespace PumpoutExtractor;

/// <summary>
///     Emits the three idempotent SQL scripts. Bulk data deliberately never enters
///     the repo — these files go to the owner's Downloads folder and are run by hand
///     (owner decision 2026-07-11). All scripts are single-transaction
///     (SET XACT_ABORT ON) and safe to re-run.
/// </summary>
public static class SqlEmit
{
    private const int MaxNameLength = 128;

    private static string Esc(string s)
    {
        return s.Replace("\r", " ").Replace("\n", " ").Replace("'", "''");
    }

    private static StringBuilder Header(string title)
    {
        var sql = new StringBuilder();
        sql.AppendLine($"-- {title}");
        sql.AppendLine($"-- Generated by tools/PumpoutExtractor on {DateTime.Now:yyyy-MM-dd}.");
        sql.AppendLine("-- Idempotent: safe to run more than once. Review before running against prod.");
        sql.AppendLine("SET XACT_ABORT ON;");
        sql.AppendLine("BEGIN TRAN;");
        sql.AppendLine();
        return sql;
    }

    /// <summary>Stable Guid for a pumpout entity so re-generated scripts stay idempotent across runs.</summary>
    public static Guid DeterministicGuid(string kind, long pumpoutId)
    {
        var bytes = MD5.HashData(Encoding.UTF8.GetBytes($"piuscores-pumpout-{kind}-{pumpoutId}"));
        return new Guid(bytes);
    }

    // ---- S1: catalog corrections (pumpout wins) --------------------------------
    public static string Corrections(Matcher matcher, List<string> skipped)
    {
        var sql = Header("S1 — catalog corrections: song artists, BPM, step artists (pumpout wins)");

        sql.AppendLine("-- ============ Song artists + BPM ============");
        foreach (var m in matcher.SongMatches.OrderBy(m => m.Prod.Name, StringComparer.Ordinal))
        {
            var prodArtist = m.Prod.Artist?.Trim();
            var pumpArtist = m.Pumpout.ArtistDisplay?.Trim();
            if (!string.IsNullOrEmpty(pumpArtist) && !string.Equals(prodArtist, pumpArtist, StringComparison.Ordinal))
            {
                if (pumpArtist.Length > MaxNameLength) { skipped.Add($"{m.Prod.Name}: artist too long"); }
                else
                {
                    sql.AppendLine($"-- {Esc(m.Prod.Name)}{(string.IsNullOrEmpty(prodArtist) ? "" : $" (was: {Esc(prodArtist)})")}");
                    sql.AppendLine($"UPDATE [scores].[Song] SET [Artist] = N'{Esc(pumpArtist)}' WHERE [Id] = '{m.Prod.Id}';");
                }
            }

            // Pumpout stores "unknown" BPM as 0; the site's Bpm value type rejects
            // non-positive values, so only genuine readings are worth filling.
            if (m.Prod.MinBpm is null && m.Pumpout.BpmMin is > 0)
            {
                sql.AppendLine($"-- {Esc(m.Prod.Name)} BPM");
                sql.AppendLine(
                    $"UPDATE [scores].[Song] SET [MinBpm] = {m.Pumpout.BpmMin}, [MaxBpm] = {m.Pumpout.BpmMax} WHERE [Id] = '{m.Prod.Id}' AND [MinBpm] IS NULL;");
            }
        }

        sql.AppendLine();
        sql.AppendLine("-- ============ Step artists ============");
        var songById = matcher.SongMatches.ToDictionary(m => m.Prod.Id, m => m.Prod.Name);
        foreach (var (prodChart, pumpChartId) in matcher.ChartMatches
                     .Select(m => (m.Prod, m.PumpoutChartId))
                     .OrderBy(m => songById.GetValueOrDefault(m.Prod.SongId, ""), StringComparer.Ordinal))
        {
            var pumpSa = MatcherContext.StepArtistOf(pumpChartId)?.Trim();
            var prodSa = prodChart.StepArtist?.Trim();
            if (string.IsNullOrEmpty(pumpSa) || string.Equals(prodSa, pumpSa, StringComparison.Ordinal)) continue;
            if (pumpSa.Length > MaxNameLength) { skipped.Add($"chart {prodChart.Id}: step artist too long"); continue; }
            var song = songById.GetValueOrDefault(prodChart.SongId, prodChart.SongId.ToString());
            sql.AppendLine($"-- {Esc(song)} {Matcher.ModeOf(prodChart.Type)}{prodChart.Level}{(string.IsNullOrEmpty(prodSa) ? "" : $" (was: {Esc(prodSa)})")}");
            sql.AppendLine($"UPDATE [scores].[Chart] SET [StepArtist] = N'{Esc(pumpSa)}' WHERE [Id] = '{prodChart.Id}';");
        }

        sql.AppendLine();
        sql.AppendLine("COMMIT TRAN;");
        return sql.ToString();
    }

    // ---- S2: OriginalMix backfill ------------------------------------------------
    public static string OriginalMixBackfill(Matcher matcher, IReadOnlyDictionary<long, PumpoutDump.Debut> debuts)
    {
        var sql = Header("S2 — Chart.OriginalMixId backfill from pumpout debut attribution (run AFTER the Mix-seeding migration is live)");
        var byMix = matcher.ChartMatches
            .Where(m => debuts.ContainsKey(m.PumpoutChartId))
            .GroupBy(m => debuts[m.PumpoutChartId].Mix)
            .OrderBy(g => g.Key.SortOrder);
        foreach (var group in byMix)
        {
            sql.AppendLine($"-- ============ Debuted in {group.Key.FullName} ({group.Count()} charts) ============");
            foreach (var m in group)
                sql.AppendLine($"UPDATE [scores].[Chart] SET [OriginalMixId] = '{group.Key.Id}' WHERE [Id] = '{m.Prod.Id}';");
            sql.AppendLine();
        }

        sql.AppendLine("COMMIT TRAN;");
        return sql.ToString();
    }

    /// <summary>A ChartMix row S3 emits — S4's vote backfill votes on exactly these.</summary>
    public sealed record BackfillRow(Guid ChartGuid, MixMap.MixDef Mix, long Level, string Mode, string? Slot,
        int PlayerCount, long PumpoutChartId, bool MatchedProd);

    // ---- S3: membership backfill + cut content ------------------------------------
    public static string MembershipBackfill(
        Matcher matcher,
        PumpoutDump dump,
        IReadOnlyDictionary<long, PumpoutDump.Debut> debuts,
        List<string> report,
        List<string> artNeeded,
        List<BackfillRow> emittedRows)
    {
        var sql = Header("S3 — ChartMix membership backfill + cut-content songs/charts (run AFTER the LegacySlot/PlayerCount/BestAttempt.MixId migration is live)");

        var prodSongIdByPump = matcher.SongMatches.ToDictionary(m => m.Pumpout.Id, m => m.Prod.Id);
        var prodChartIdByPump = matcher.ChartMatches.ToDictionary(m => m.PumpoutChartId, m => m.Prod.Id);

        // memberships across every pumpout-backed mix (incl. XX gap-fill; Phoenix+ is prod's own domain)
        var memberships = MixMap.All
            .Where(m => m.PumpoutMixId is not null)
            .SelectMany(m => dump.MembershipsOf(m).Select(mem => (Mix: m, mem.ChartId, mem.LastState)))
            .Where(x => !matcher.QuarantinedPumpoutChartIds.Contains(x.ChartId))
            .ToList();

        var neededCharts = memberships.Select(x => x.ChartId).Distinct()
            .Where(id => !prodChartIdByPump.ContainsKey(id))
            .ToList();
        var neededSongs = neededCharts.Select(id => dump.Charts[id].SongId).Distinct()
            .Where(id => !prodSongIdByPump.ContainsKey(id) && !matcher.QuarantinedPumpoutSongIds.Contains(id))
            .ToList();

        // ---- new songs ------------------------------------------------------------
        sql.AppendLine($"-- ============ Cut-content songs ({neededSongs.Count}) ============");
        foreach (var songId in neededSongs.OrderBy(id => dump.Songs[id].Title, StringComparer.Ordinal))
        {
            var song = dump.Songs[songId];
            var guid = DeterministicGuid("song", songId);
            prodSongIdByPump[songId] = guid;
            var name = song.Cut switch
            {
                "FullSong" when !song.Title.Contains("FULL SONG", StringComparison.OrdinalIgnoreCase) => $"{song.Title} - FULL SONG -",
                "ShortCut" when !song.Title.Contains("SHORT CUT", StringComparison.OrdinalIgnoreCase) => $"{song.Title} - SHORT CUT -",
                _ => song.Title
            };
            if (name.Length > MaxNameLength) { report.Add($"SKIPPED song (name too long): {name}"); continue; }
            var imageName = new string(name.Where(char.IsLetterOrDigit).ToArray());
            if (imageName.Length == 0) imageName = $"song{songId}"; // "!" sanitizes to nothing
            var imagePath = $"https://piuimages.arroweclip.se/songs/{imageName}.png";
            artNeeded.Add($"{imageName}.png <= https://pumpout2020.anyhowstep.com{song.CardPaths.FirstOrDefault() ?? "(no card)"} ({Esc(song.Title)})");
            // Pumpout stores "unknown" BPM as 0, but the site's Bpm value type
            // (correctly) rejects non-positive values — import unknowns as NULL.
            var bpmMin = song.BpmMin is > 0 ? song.BpmMin.ToString() : "NULL";
            var bpmMax = song.BpmMax is > 0 ? song.BpmMax.ToString() : "NULL";
            var artist = song.ArtistDisplay is null ? "NULL" : $"N'{Esc(song.ArtistDisplay)}'";
            sql.AppendLine($"IF NOT EXISTS (SELECT 1 FROM [scores].[Song] WHERE [Id] = '{guid}')");
            sql.AppendLine(
                $"    INSERT INTO [scores].[Song] ([Id], [Name], [ImagePath], [Type], [Duration], [Artist], [MinBpm], [MaxBpm]) VALUES ('{guid}', N'{Esc(name)}', N'{imagePath}', '{song.Cut}', 0, {artist}, {bpmMin}, {bpmMax});");
        }

        // ---- new charts -------------------------------------------------------------
        sql.AppendLine();
        sql.AppendLine($"-- ============ Cut-content charts ({neededCharts.Count}) ============");
        var insertedCharts = new HashSet<long>();
        foreach (var chartId in neededCharts)
        {
            var chart = dump.Charts[chartId];
            if (!prodSongIdByPump.TryGetValue(chart.SongId, out var songGuid))
            {
                report.Add($"SKIPPED chart {chartId} ({dump.Songs[chart.SongId].Title}): song quarantined/skipped");
                continue;
            }

            var last = dump.LastKnownState(chartId);
            if (last.Mode is null) { report.Add($"SKIPPED chart {chartId} ({dump.Songs[chart.SongId].Title}): no rating history"); continue; }
            var type = Matcher.ProdTypeOf(last.Mode);
            var level = last.Level ?? (type == "CoOp" ? last.PlayerCount : 1);
            var guid = DeterministicGuid("chart", chartId);
            prodChartIdByPump[chartId] = guid;
            insertedCharts.Add(chartId);
            var stepArtist = chart.StepArtistDisplay is { Length: <= MaxNameLength } sa ? $"N'{Esc(sa)}'" : "NULL";
            var debutGuid = debuts.TryGetValue(chartId, out var debut) ? debut.Mix.Id : MixMap.Phoenix;
            sql.AppendLine($"-- {Esc(dump.Songs[chart.SongId].Title)} {last.Mode}{last.Level?.ToString() ?? "??"}");
            sql.AppendLine($"IF NOT EXISTS (SELECT 1 FROM [scores].[Chart] WHERE [Id] = '{guid}')");
            sql.AppendLine(
                $"    INSERT INTO [scores].[Chart] ([Id], [SongId], [Level], [Type], [StepArtist], [OriginalMixId], [PlayerCount]) VALUES ('{guid}', '{songGuid}', {level}, '{type}', {stepArtist}, '{debutGuid}', {last.PlayerCount});");
        }

        // ---- membership rows -----------------------------------------------------------
        sql.AppendLine();
        var rows = 0;
        foreach (var mixGroup in memberships.GroupBy(x => x.Mix).OrderBy(g => g.Key.SortOrder))
        {
            sql.AppendLine($"-- ============ {mixGroup.Key.FullName} ============");
            foreach (var (mix, chartId, state) in mixGroup)
            {
                if (!prodChartIdByPump.TryGetValue(chartId, out var chartGuid)) continue;
                var mode = state.Mode;
                if (mode is null) { report.Add($"SKIPPED row {mix.ShortName}/{chartId}: no mode"); continue; }
                var level = state.Level ?? (mode is "C" or "R" ? state.PlayerCount : (long?)null);
                if (level is null)
                {
                    report.Add($"SKIPPED row {mix.ShortName}/{dump.Songs[dump.Charts[chartId].SongId].Title} {mode}: unrated non-coop");
                    continue;
                }

                var slot = state.Slot is null ? "NULL" : $"N'{Esc(state.Slot)}'";
                var rowGuid = DeterministicGuid("chartmix", chartId * 1000 + mix.SortOrder);
                sql.AppendLine(
                    $"IF NOT EXISTS (SELECT 1 FROM [scores].[ChartMix] WHERE [ChartId] = '{chartGuid}' AND [MixId] = '{mix.Id}')");
                sql.AppendLine(
                    $"    INSERT INTO [scores].[ChartMix] ([Id], [ChartId], [MixId], [Level], [NoteCount], [LegacySlot]) VALUES ('{rowGuid}', '{chartGuid}', '{mix.Id}', {level}, NULL, {slot});");
                emittedRows.Add(new BackfillRow(chartGuid, mix, level.Value, mode, state.Slot, state.PlayerCount,
                    chartId, prodChartIdByPump.ContainsKey(chartId) && !insertedCharts.Contains(chartId)));
                rows++;
            }

            sql.AppendLine();
        }

        report.Insert(0, $"membership rows emitted: {rows}; new songs: {neededSongs.Count}; new charts: {insertedCharts.Count}");
        sql.AppendLine("COMMIT TRAN;");
        return sql.ToString();
    }

    // ---- S4: hindsight difficulty votes (owner decision: vote-based legacy tier data) ---
    // One PumpoutBackfill vote per S3 ChartMix row, scaled by where the chart's rating
    // ended up (prod's current level for still-alive charts, pumpout's last-known state
    // for cut ones). Pre-Exceed rows and player-count co-ops vote Medium — their scales
    // don't compare. Aggregates are recomputed set-based with the exact
    // ReCalculateChartRatingHandler math (level + .5 + adjustment; population stddev).
    public static readonly Guid BackfillUserId = DeterministicGuid("backfill-user", 0);

    public static string VoteBackfill(
        IReadOnlyList<BackfillRow> rows,
        IReadOnlyDictionary<Guid, int> prodLevelByChartGuid,
        PumpoutDump dump,
        List<string> report)
    {
        var sql = Header("S4 — PumpoutBackfill hindsight difficulty votes (run AFTER s3)");

        sql.AppendLine("-- The synthetic voter. Not public, no game tag; delete this user to retract every backfill vote.");
        sql.AppendLine($"IF NOT EXISTS (SELECT 1 FROM [scores].[User] WHERE [Id] = '{BackfillUserId}')");
        sql.AppendLine(
            $"    INSERT INTO [scores].[User] ([Id], [Name], [IsPublic], [ProfileImage], [IsContentLocked], [ClaimsInvalidatedAt]) VALUES ('{BackfillUserId}', N'PumpoutBackfill', 0, N'https://piuimages.arroweclip.se/avatars/4f617606e7751b2dc2559d80f09c40bf.png', 0, '2026-07-11');");
        sql.AppendLine();

        var distribution = new Dictionary<int, int>();
        foreach (var row in rows)
        {
            var scale = ScaleFor(row);
            distribution[scale] = distribution.GetValueOrDefault(scale) + 1;
            var voteGuid = DeterministicGuid("vote", row.PumpoutChartId * 1000 + row.Mix.SortOrder);
            sql.AppendLine(
                $"IF NOT EXISTS (SELECT 1 FROM [scores].[UserChartDifficultyRating] WHERE [UserId] = '{BackfillUserId}' AND [ChartId] = '{row.ChartGuid}' AND [MixId] = '{row.Mix.Id}')");
            sql.AppendLine(
                $"    INSERT INTO [scores].[UserChartDifficultyRating] ([Id], [UserId], [ChartId], [MixId], [Scale]) VALUES ('{voteGuid}', '{BackfillUserId}', '{row.ChartGuid}', '{row.Mix.Id}', {scale});");
        }

        sql.AppendLine();
        sql.AppendLine("-- Recompute aggregates for every (chart, mix) the backfill touched, folding in any");
        sql.AppendLine("-- organic votes (XX-era voting predates this). Mirrors ReCalculateChartRatingHandler.");
        sql.AppendLine(@"
;WITH affected AS (
    SELECT DISTINCT v.[ChartId], v.[MixId]
    FROM [scores].[UserChartDifficultyRating] v
    WHERE v.[UserId] = '" + BackfillUserId + @"'
), calc AS (
    SELECT v.[ChartId], v.[MixId],
        AVG(cm.[Level] + 0.5 + CASE v.[Scale]
            WHEN -4 THEN -2.0 WHEN -3 THEN -1.0 WHEN -2 THEN -0.5 WHEN -1 THEN -0.25
            WHEN 0 THEN 0.0 WHEN 1 THEN 0.25 WHEN 2 THEN 0.5 WHEN 3 THEN 1.0 WHEN 4 THEN 2.0 END) AS [Difficulty],
        COUNT(*) AS [Cnt],
        ISNULL(STDEVP(CASE v.[Scale]
            WHEN -4 THEN -2.0 WHEN -3 THEN -1.0 WHEN -2 THEN -0.5 WHEN -1 THEN -0.25
            WHEN 0 THEN 0.0 WHEN 1 THEN 0.25 WHEN 2 THEN 0.5 WHEN 3 THEN 1.0 WHEN 4 THEN 2.0 END), 0) AS [SD]
    FROM [scores].[UserChartDifficultyRating] v
    JOIN affected a ON a.[ChartId] = v.[ChartId] AND a.[MixId] = v.[MixId]
    JOIN [scores].[ChartMix] cm ON cm.[ChartId] = v.[ChartId] AND cm.[MixId] = v.[MixId]
    GROUP BY v.[ChartId], v.[MixId]
)
MERGE [scores].[ChartDifficultyRating] AS t
USING calc AS s ON t.[ChartId] = s.[ChartId] AND t.[MixId] = s.[MixId]
WHEN MATCHED THEN UPDATE SET t.[Difficulty] = s.[Difficulty], t.[Count] = s.[Cnt], t.[StandardDeviation] = s.[SD]
WHEN NOT MATCHED THEN INSERT ([ChartId], [MixId], [Difficulty], [Count], [StandardDeviation])
    VALUES (s.[ChartId], s.[MixId], s.[Difficulty], s.[Cnt], s.[SD]);");
        sql.AppendLine();
        sql.AppendLine("COMMIT TRAN;");

        report.Add("vote distribution (scale: count): " + string.Join(", ",
            distribution.OrderBy(kv => kv.Key).Select(kv => $"{kv.Key}: {kv.Value}")));
        return sql.ToString();

        int ScaleFor(BackfillRow row)
        {
            // Cross-scale comparisons are lies: pre-Exceed eras rate 1-10 on their own
            // ladder, and mainline co-ops store player count in Level.
            if (row.Mix.PreExceedSlots || row.Mode == "C") return 0;

            long? final = null;
            if (row.MatchedProd && prodLevelByChartGuid.TryGetValue(row.ChartGuid, out var prodLevel))
            {
                final = prodLevel;
            }
            else
            {
                var last = dump.LastKnownState(row.PumpoutChartId);
                if (last.Mode == row.Mode) final = last.Level;
            }

            if (final is null) return 0;
            return (final.Value - row.Level) switch
            {
                <= -2 => -4, // 2+ Levels Overrated
                -1 => -3, // 1 Level Overrated
                1 => 3, // 1 Level Underrated
                >= 2 => 4, // 2+ Levels Underrated
                _ => 0 // Medium — "landed where it was rated"
            };
        }
    }
}

/// <summary>Step-artist lookup shared with S1 emission without threading the dump through every call.</summary>
public static class MatcherContext
{
    private static IReadOnlyDictionary<long, PumpoutDump.ChartInfo>? _charts;

    public static void Initialize(PumpoutDump dump)
    {
        _charts = dump.Charts;
    }

    public static string? StepArtistOf(long chartId)
    {
        return _charts is not null && _charts.TryGetValue(chartId, out var c) ? c.StepArtistDisplay : null;
    }
}
